trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/alpine/*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/alpine/*'

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmd64Pool:
      name: ubuntu-latest